"""Constants for Phase 4 aggregation."""

AGGREGATION_VERSION = "agg_v1"
AGGREGATION_EVENT_TYPE = "aggregate_audit"
AGGREGATION_EVENT_SCHEMA_VERSION = "phase4.aggregation_event.v1"
LINEAGE_MANIFEST_VERSION = "lineage_manifest_v1"

JOB_STATUS_STARTED = "STARTED"
JOB_STATUS_INTENT_RECORDED = "INTENT_RECORDED"
JOB_STATUS_INVOCATION_REQUESTED = "INVOCATION_REQUESTED"
JOB_STATUS_INVOCATION_FAILED = "INVOCATION_FAILED"
JOB_STATUS_COMPLETED = "COMPLETED"
JOB_STATUS_FAILED = "FAILED"
JOB_STATUS_INELIGIBLE = "INELIGIBLE"
JOB_STATUS_DUPLICATE_COMPLETED = "DUPLICATE_COMPLETED"
JOB_STATUS_CONFLICT = "CONFLICT"

FAILURE_CATEGORY_EVIDENCE_PRODUCING = "EVIDENCE_PRODUCING"
FAILURE_CATEGORY_EVIDENCE_TRANSFORMING = "EVIDENCE_TRANSFORMING"

EVIDENCE_PRODUCING_REASON_CODES = frozenset(
    {
        "EXECUTION_COUNT_MISMATCH_COMPLETED_RUNS",
        "EXECUTION_COUNT_MISMATCH_RAW_RESULTS",
        "ORPHANED_RAW_RESULT_RECORDS",
        "MISSING_RAW_EVIDENCE",
        "NO_COMPLETED_RUN_EVIDENCE",
        "NO_RAW_RESULT_EVIDENCE",
        "INCOMPLETE_EXECUTION_EVIDENCE",
        "LINEAGE_INCOMPLETE",
        "LINEAGE_CORRUPT",
        "DUPLICATE_RAW_RESULT_REFERENCE",
        "MISSING_AUDIT_EXECUTION_ID",
        "MISSING_CONFIG_VERSION",
        "INVALID_RAW_RESULT_ENVELOPE",
        "INVALID_RAW_RESULT_RECORD",
        "UNSAFE_RAW_RESULT_S3_KEY",
    }
)

EVIDENCE_TRANSFORMING_REASON_CODES = frozenset(
    {
        "AGGREGATION_TRIGGER_INVOCATION_FAILED",
        "AGGREGATION_TIMEOUT",
        "TRANSIENT_STORAGE_FAILURE",
        "WORKER_FAILURE",
        "AGGREGATE_WRITE_CONFLICT",
        "AGGREGATE_SET_INCOMPLETE_CONFLICT",
        "CONDITIONAL_WRITE_FAILED",
        "AGGREGATE_SET_TOO_LARGE",
        "LINEAGE_MANIFEST_TOO_LARGE",
    }
)

MISSING_CLASSIFICATION = "MISSING_FAILURE_CLASSIFICATION"
UNKNOWN_CLASSIFICATION = "UNKNOWN_FAILURE_CLASSIFICATION"
NO_STATUS = "NO_STATUS"
UNKNOWN_ENDPOINT = "unknown"

MAX_MANIFEST_BYTES = 300_000
MAX_AGGREGATE_RECORDS = 100
MAX_AGGREGATE_ITEM_BYTES = 300_000
MAX_AGGREGATE_TRANSACTION_BYTES = 3_800_000
MAX_ENDPOINT_ID_LENGTH = 128
