"""Constants for Phase 4 aggregation."""

AGGREGATION_VERSION = "agg_v1"
AGGREGATION_EVENT_TYPE = "aggregate_audit"
AGGREGATION_EVENT_SCHEMA_VERSION = "phase4.aggregation_event.v1"
LINEAGE_MANIFEST_VERSION = "lineage_manifest_v1"

JOB_STATUS_STARTED = "STARTED"
JOB_STATUS_COMPLETED = "COMPLETED"
JOB_STATUS_FAILED = "FAILED"
JOB_STATUS_INELIGIBLE = "INELIGIBLE"
JOB_STATUS_DUPLICATE_COMPLETED = "DUPLICATE_COMPLETED"
JOB_STATUS_CONFLICT = "CONFLICT"

MISSING_CLASSIFICATION = "MISSING_FAILURE_CLASSIFICATION"
UNKNOWN_CLASSIFICATION = "UNKNOWN_FAILURE_CLASSIFICATION"
NO_STATUS = "NO_STATUS"
UNKNOWN_ENDPOINT = "unknown"

MAX_MANIFEST_BYTES = 300_000
MAX_AGGREGATE_RECORDS = 100
MAX_AGGREGATE_ITEM_BYTES = 300_000
MAX_ENDPOINT_ID_LENGTH = 128
