"""Phase 1 core engine constants."""

RAW_RESULT_VERSION = "v1"

RUN_STATUS_STARTED = "STARTED"
RUN_STATUS_COMPLETED = "COMPLETED"
RUN_STATUS_FAILED = "FAILED"
RUN_STATUSES = (RUN_STATUS_STARTED, RUN_STATUS_COMPLETED, RUN_STATUS_FAILED)

FAILURE_PASS = "PASS"
FAILURE_ASSERTION = "ASSERTION_FAILURE"
FAILURE_HTTP = "HTTP_ERROR"
FAILURE_TIMEOUT = "TIMEOUT"
FAILURE_CONNECTION = "CONNECTION_ERROR"
FAILURE_INVALID_RESPONSE = "INVALID_RESPONSE"
FAILURE_RUNNER = "RUNNER_ERROR"
FAILURE_PAYLOAD_VALIDATION = "PAYLOAD_VALIDATION_ERROR"
ENDPOINT_FAILURE_TYPES = (
    FAILURE_PASS,
    FAILURE_ASSERTION,
    FAILURE_HTTP,
    FAILURE_TIMEOUT,
    FAILURE_CONNECTION,
    FAILURE_INVALID_RESPONSE,
    FAILURE_RUNNER,
    FAILURE_PAYLOAD_VALIDATION,
)

DUPLICATE_RUN_ID = "DUPLICATE_RUN_ID"

DEFAULT_TIMEOUT_SECONDS = 10
MAX_TIMEOUT_SECONDS = 30
DEFAULT_RETRIES = 0
MAX_RETRIES = 3

LOG_CATEGORY_INTERNAL = "internal_operational_logs"
LOG_CATEGORY_CLIENT_SAFE = "client_safe_logs"
LOG_CATEGORIES = (LOG_CATEGORY_INTERNAL, LOG_CATEGORY_CLIENT_SAFE)

SUPPORTED_HTTP_METHODS = ("GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS")

RAW_RESULT_KEY_TEMPLATE = "raw-results/{client_id}/{audit_id}/{run_id}/results.json"
CLIENT_CONFIG_KEY_TEMPLATE = "configs/{client_id}/client_config.json"
AUDIT_CONFIG_KEY_TEMPLATE = "configs/{client_id}/audits/{audit_id}/audit_config.json"
ENDPOINTS_CONFIG_KEY_TEMPLATE = "configs/{client_id}/audits/{audit_id}/endpoints.json"
