"""Platform Integrity Certificate Pydantic models for Phase 7 cert_v1 schema.

Model stratification:
  CertificationDomainResult    — per-domain verification result from the domain executor
  CertificationIdentity        — certificate identity fields (Phase 7-generated)
  CertificationResult          — terminal state, summary, and disclosed failures
  CertificationReportReference — Phase 6 report reference fields (by key only)
  CertificationAuditProvenance — audit identity fields carried in the certificate
  PlatformIntegrityCertificate — the complete, immutable certificate artifact

All magic values are imported from constants.py. No inline constants.

Serialization: certificate.to_dict() returns model.model_dump() for use with
json.dumps(cert.to_dict(), sort_keys=True, indent=2) in the engine/publisher layer.
"""

from __future__ import annotations

from pydantic import BaseModel, field_validator, model_validator

from release_confidence_platform.audit_platform_integrity.constants import (
    CERT_DOMAIN_IDENTIFIERS,
    CERTIFICATION_SUMMARY_MAP,
    CERTIFICATE_VERSION,
    DOMAIN_STATUSES,
    TERMINAL_STATES,
)


# ---------------------------------------------------------------------------
# Domain Result
# ---------------------------------------------------------------------------


class CertificationDomainResult(BaseModel):
    """Per-domain verification result produced by a single certification domain check."""

    domain: str
    status: str
    checks_performed: int
    checks_passed: int
    failure_details: list[str]
    evidence_refs: list[str]

    @field_validator("domain")
    @classmethod
    def _domain_in_bounded_set(cls, v: str) -> str:
        if v not in CERT_DOMAIN_IDENTIFIERS:
            raise ValueError(
                f"domain must be one of {list(CERT_DOMAIN_IDENTIFIERS)}, got {v!r}"
            )
        return v

    @field_validator("status")
    @classmethod
    def _status_in_bounded_set(cls, v: str) -> str:
        if v not in DOMAIN_STATUSES:
            raise ValueError(
                f"status must be one of {sorted(DOMAIN_STATUSES)}, got {v!r}"
            )
        return v

    @field_validator("checks_performed")
    @classmethod
    def _checks_performed_non_negative(cls, v: int) -> int:
        if v < 0:
            raise ValueError(
                f"checks_performed must be >= 0, got {v}"
            )
        return v

    @field_validator("checks_passed")
    @classmethod
    def _checks_passed_non_negative(cls, v: int) -> int:
        if v < 0:
            raise ValueError(
                f"checks_passed must be >= 0, got {v}"
            )
        return v

    @model_validator(mode="after")
    def _checks_passed_le_checks_performed(self) -> CertificationDomainResult:
        if self.checks_passed > self.checks_performed:
            raise ValueError(
                f"checks_passed ({self.checks_passed}) must be <= "
                f"checks_performed ({self.checks_performed})"
            )
        return self


# ---------------------------------------------------------------------------
# Certificate Identity
# ---------------------------------------------------------------------------


class CertificationIdentity(BaseModel):
    """Certificate identity fields generated by Phase 7 at certification time."""

    certificate_id: str
    certificate_version: str
    generated_at: str
    generator_version: str

    @field_validator("certificate_version")
    @classmethod
    def _certificate_version_must_be_v1(cls, v: str) -> str:
        if v != CERTIFICATE_VERSION:
            raise ValueError(
                f"certificate_version must be '{CERTIFICATE_VERSION}', got {v!r}"
            )
        return v


# ---------------------------------------------------------------------------
# Certification Result
# ---------------------------------------------------------------------------


class CertificationResult(BaseModel):
    """Terminal state, certification summary, and disclosed failures."""

    terminal_state: str
    certification_summary: str
    disclosed_failures: list[str]

    @field_validator("terminal_state")
    @classmethod
    def _terminal_state_in_bounded_set(cls, v: str) -> str:
        if v not in TERMINAL_STATES:
            raise ValueError(
                f"terminal_state must be one of {sorted(TERMINAL_STATES)}, got {v!r}"
            )
        return v

    @field_validator("disclosed_failures", mode="before")
    @classmethod
    def _disclosed_failures_members_in_domain_set(cls, v: object) -> object:
        if isinstance(v, list):
            for item in v:
                if item not in CERT_DOMAIN_IDENTIFIERS:
                    raise ValueError(
                        f"disclosed_failures member must be one of "
                        f"{list(CERT_DOMAIN_IDENTIFIERS)}, got {item!r}"
                    )
        return v

    @model_validator(mode="after")
    def _validate_summary_and_failures(self) -> CertificationResult:
        expected_summary = CERTIFICATION_SUMMARY_MAP.get(self.terminal_state)
        if expected_summary is not None and self.certification_summary != expected_summary:
            raise ValueError(
                f"certification_summary for terminal_state={self.terminal_state!r} "
                f"must be {expected_summary!r}, got {self.certification_summary!r}"
            )
        if self.terminal_state == "CERTIFIED" and self.disclosed_failures:
            raise ValueError(
                "disclosed_failures must be empty when terminal_state is 'CERTIFIED', "
                f"got {self.disclosed_failures!r}"
            )
        return self


# ---------------------------------------------------------------------------
# Report Reference
# ---------------------------------------------------------------------------


class CertificationReportReference(BaseModel):
    """Reference to the Phase 6 report this certificate covers (by key only).

    The Phase 6 report artifact content is never embedded in the certificate.
    Consumers use s3_report_artifact_ref to retrieve the report artifact directly.
    """

    report_id: str
    report_version: str
    s3_report_artifact_ref: str
    intelligence_version: str
    aggregate_set_hash: str


# ---------------------------------------------------------------------------
# Audit Provenance
# ---------------------------------------------------------------------------


class CertificationAuditProvenance(BaseModel):
    """Audit identity fields carried in the certificate for full provenance tracing."""

    client_id: str
    audit_id: str
    audit_execution_id: str
    config_version: str
    aggregation_version: str
    intelligence_version: str
    report_version: str


# ---------------------------------------------------------------------------
# Platform Integrity Certificate (root artifact)
# ---------------------------------------------------------------------------


class PlatformIntegrityCertificate(BaseModel):
    """The complete, immutable Platform Integrity Certificate artifact (cert_v1).

    Produced by Phase 7 certification engine. Written to S3 under the integrity/
    key prefix. Never overwritten; force re-certification produces a new artifact
    at a new key with a new certificate_id.

    JSON serialization: json.dumps(cert.to_dict(), sort_keys=True, indent=2)
    """

    identity: CertificationIdentity
    result: CertificationResult
    report_reference: CertificationReportReference
    audit_provenance: CertificationAuditProvenance
    domain_results: list[CertificationDomainResult]
    certjob_id: str

    @model_validator(mode="after")
    def _validate_domain_results(self) -> PlatformIntegrityCertificate:
        results = self.domain_results

        if len(results) != len(CERT_DOMAIN_IDENTIFIERS):
            raise ValueError(
                f"domain_results must contain exactly {len(CERT_DOMAIN_IDENTIFIERS)} "
                f"elements (one per domain), got {len(results)}"
            )

        seen_domains: list[str] = [r.domain for r in results]
        if len(seen_domains) != len(set(seen_domains)):
            duplicates = [d for d in seen_domains if seen_domains.count(d) > 1]
            raise ValueError(
                f"domain_results contains duplicate domain identifiers: {duplicates!r}"
            )

        missing = [d for d in CERT_DOMAIN_IDENTIFIERS if d not in seen_domains]
        if missing:
            raise ValueError(
                f"domain_results is missing required domain identifiers: {missing!r}"
            )

        return self

    def to_dict(self) -> dict:
        """Return a plain dict representation suitable for JSON serialization.

        Callers should use: json.dumps(cert.to_dict(), sort_keys=True, indent=2)
        """
        return self.model_dump()
