Resources:
  MetadataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.metadataTableName}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
Outputs:
  MetadataTableName:
    Description: Runtime metadata DynamoDB table name.
    Value: ${self:custom.metadataTableName}
  MetadataTableArn:
    Description: Runtime metadata DynamoDB table ARN.
    Value:
      Fn::GetAtt:
        - MetadataTable
        - Arn
