Resources:
  RawResultsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.rawResultsBucketName}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
Outputs:
  RawResultsBucketName:
    Description: Runtime raw results and backend config bucket name.
    Value: ${self:custom.rawResultsBucketName}
  RawResultsBucketArn:
    Description: Runtime raw results and backend config bucket ARN.
    Value: arn:aws:s3:::${self:custom.rawResultsBucketName}
