"""Phase 6 Report Builder — transforms Phase 5 intelligence artifact into ReleaseConfidenceReport DTO.

The builder is a pure transformation function. It performs no I/O and never calls
datetime.now() or utc_now_iso(). All time values are sourced from the artifact or
the generated_at parameter supplied by the engine.

Decimal-serialised string fields from Phase 5 (score/rate values stored as strings)
are converted to float here. This is the single point of that conversion.
"""

from __future__ import annotations

from typing import Any

from release_confidence_platform.deterministic_reporting.constants import (
    REPORT_VERSION,
    SCORE_LABEL_DESCRIPTIONS,
)
from release_confidence_platform.deterministic_reporting.identity import generate_report_id
from release_confidence_platform.deterministic_reporting.models import (
    AuditReliabilityOverview,
    BurstAnalysis,
    CompositeScoreSection,
    ConsistencyAnalysis,
    EndpointScore,
    EndpointSection,
    ExecutiveSummary,
    InputLineageSection,
    IntelligenceProvenance,
    MethodologyDisclosure,
    ReleaseConfidenceReport,
    ReliabilityMetrics,
    ReportIdentity,
    StabilityAnalysis,
)

_GENERATOR_VERSION = "1.0.0"


class ReportBuilder:
    """Transforms a Phase 5 intelligence artifact dict into a ReleaseConfidenceReport DTO."""

    def build(
        self,
        intelligence_artifact: dict[str, Any],
        report_job_id: str,
        generated_at: str,
    ) -> ReleaseConfidenceReport:
        """Build a ReleaseConfidenceReport from the Phase 5 intelligence artifact.

        Args:
            intelligence_artifact: Deserialised Phase 5 S3 artifact dict.
            report_job_id: The report job identifier generated by the engine.
            generated_at: ISO 8601 UTC timestamp supplied by the engine (never derived here).

        Returns:
            Fully populated ReleaseConfidenceReport DTO.
        """
        artifact = intelligence_artifact

        # ------------------------------------------------------------------
        # Layer 1: Report Identity (Phase 6-generated)
        # ------------------------------------------------------------------
        identity = ReportIdentity(
            report_id=generate_report_id(),
            report_version=REPORT_VERSION,
            generated_at=generated_at,
            generator_version=_GENERATOR_VERSION,
        )

        # ------------------------------------------------------------------
        # Layer 2: Intelligence Provenance (Phase 5 pass-through)
        # ------------------------------------------------------------------
        composite_score_raw = artifact["composite_score"]
        intelligence_provenance = IntelligenceProvenance(
            intelligence_version=artifact["intelligence_version"],
            intelligence_job_id=artifact["intelligence_job_id"],
            client_id=artifact["client_id"],
            audit_id=artifact["audit_id"],
            audit_execution_id=artifact["audit_execution_id"],
            config_version=artifact["config_version"],
            aggregation_version=artifact["aggregation_version"],
            aggregate_set_hash=composite_score_raw["aggregate_set_hash"],
            intelligence_completed_at=artifact["generated_at"],
        )

        # ------------------------------------------------------------------
        # Layer 3: Executive Summary
        # ------------------------------------------------------------------
        score_label = composite_score_raw["score_label"]
        audit_reliability_raw = artifact["audit_reliability_summary"]
        executive_summary = ExecutiveSummary(
            score_label=score_label,
            composite_score_value=float(composite_score_raw["value"]),
            endpoint_count=composite_score_raw["endpoint_count"],
            audit_success_rate=float(audit_reliability_raw["audit_success_rate"]),
            total_executions=audit_reliability_raw["total_executions"],
            score_label_description=SCORE_LABEL_DESCRIPTIONS[score_label],
        )

        # ------------------------------------------------------------------
        # Layer 4: Audit Reliability Overview
        # ------------------------------------------------------------------
        audit_reliability_overview = AuditReliabilityOverview(
            total_executions=audit_reliability_raw["total_executions"],
            total_pass=audit_reliability_raw["total_pass"],
            total_fail=audit_reliability_raw["total_fail"],
            total_timeout=audit_reliability_raw["total_timeout"],
            total_network_failure=audit_reliability_raw["total_network_failure"],
            audit_success_rate=float(audit_reliability_raw["audit_success_rate"]),
            endpoint_count=audit_reliability_raw["endpoint_count"],
            audit_latency_mean_ms=audit_reliability_raw.get("audit_latency_mean_ms"),
            audit_latency_p95_ms=audit_reliability_raw.get("audit_latency_p95_ms"),
            audit_latency_p99_ms=audit_reliability_raw.get("audit_latency_p99_ms"),
            source_field_refs=audit_reliability_raw["source_field_refs"],
        )

        # ------------------------------------------------------------------
        # Layer 4: Composite Score Section
        # ------------------------------------------------------------------
        composite_score = CompositeScoreSection(
            value=float(composite_score_raw["value"]),
            score_label=composite_score_raw["score_label"],
            intelligence_version=composite_score_raw["intelligence_version"],
            aggregation_version=composite_score_raw["aggregation_version"],
            aggregate_set_hash=composite_score_raw["aggregate_set_hash"],
            endpoint_count=composite_score_raw["endpoint_count"],
            component_breakdown=composite_score_raw["component_breakdown"],
        )

        # ------------------------------------------------------------------
        # Layer 4: Endpoints (Phase 5 already sorts by endpoint_id)
        # ------------------------------------------------------------------
        endpoints: list[EndpointSection] = []
        for entry in artifact["endpoints"]:
            rm_raw = entry["reliability_metrics"]
            success_rate_raw = rm_raw.get("success_rate")
            reliability_metrics = ReliabilityMetrics(
                execution_count=rm_raw["execution_count"],
                pass_count=rm_raw["pass_count"],
                fail_count=rm_raw["fail_count"],
                timeout_count=rm_raw["timeout_count"],
                success_rate=float(success_rate_raw) if success_rate_raw is not None else None,
                success_rate_numerator=rm_raw["success_rate_numerator"],
                success_rate_denominator=rm_raw["success_rate_denominator"],
                latency_min_ms=rm_raw.get("latency_min_ms"),
                latency_max_ms=rm_raw.get("latency_max_ms"),
                latency_mean_ms=rm_raw.get("latency_mean_ms"),
                latency_median_ms=rm_raw.get("latency_median_ms"),
                latency_p95_ms=rm_raw.get("latency_p95_ms"),
                latency_p99_ms=rm_raw.get("latency_p99_ms"),
                latency_count=rm_raw["latency_count"],
                failure_classification_breakdown=rm_raw["failure_classification_breakdown"],
                http_response_distribution=rm_raw["http_response_distribution"],
                source_field_refs=rm_raw["source_field_refs"],
            )

            sa_raw = entry["stability_analysis"]
            stability_analysis = StabilityAnalysis(
                success_rate_stability_label=sa_raw["success_rate_stability_label"],
                latency_stability_label=sa_raw["latency_stability_label"],
                methodology_trace=sa_raw["methodology_trace"],
            )

            ba_raw = entry["burst_analysis"]
            burst_analysis = BurstAnalysis(
                failure_burst_label=ba_raw["failure_burst_label"],
                latency_spike_label=ba_raw["latency_spike_label"],
                methodology_trace=ba_raw["methodology_trace"],
            )

            ca_raw = entry["consistency_analysis"]
            consistency_analysis = ConsistencyAnalysis(
                consistency_label=ca_raw["consistency_label"],
                methodology_trace=ca_raw["methodology_trace"],
            )

            es_raw = entry["endpoint_score"]
            endpoint_score = EndpointScore(
                composite_score=float(es_raw["composite_score"]),
                reliability_score=float(es_raw["reliability_score"]),
                stability_score=float(es_raw["stability_score"]),
                burst_score=float(es_raw["burst_score"]),
                consistency_score=float(es_raw["consistency_score"]),
                score_derivation=es_raw["score_derivation"],
            )

            endpoints.append(
                EndpointSection(
                    endpoint_id=entry["endpoint_id"],
                    reliability_metrics=reliability_metrics,
                    stability_analysis=stability_analysis,
                    burst_analysis=burst_analysis,
                    consistency_analysis=consistency_analysis,
                    endpoint_score=endpoint_score,
                )
            )

        # ------------------------------------------------------------------
        # Layers 4/5: Input Lineage Section
        # ------------------------------------------------------------------
        lineage_raw = artifact["input_lineage"]
        input_lineage = InputLineageSection(
            aggregate_set_hash=lineage_raw["aggregate_set_hash"],
            aggregation_job_id=lineage_raw["aggregation_job_id"],
            aggregation_version=lineage_raw["aggregation_version"],
            aggregate_set_completion_created_at=lineage_raw["aggregate_set_completion_created_at"],
            endpoint_aggregate_count=lineage_raw["endpoint_aggregate_count"],
            source_raw_result_count=lineage_raw["source_raw_result_count"],
            audit_lineage_manifest_ref=lineage_raw.get("audit_lineage_manifest_ref") or {},
        )

        # ------------------------------------------------------------------
        # Layer 5: Methodology Disclosure (verbatim pass-through)
        # ------------------------------------------------------------------
        md_raw = artifact["methodology_disclosure"]
        methodology_disclosure = MethodologyDisclosure(
            intelligence_version=md_raw["intelligence_version"],
            scoring=md_raw["scoring"],
            stability_label_definitions=md_raw["stability_label_definitions"],
            burst_label_definitions=md_raw["burst_label_definitions"],
            consistency_label_definitions=md_raw["consistency_label_definitions"],
            label_to_score_mapping=md_raw["label_to_score_mapping"],
            limitations=md_raw["limitations"],
        )

        return ReleaseConfidenceReport(
            identity=identity,
            intelligence_provenance=intelligence_provenance,
            executive_summary=executive_summary,
            audit_reliability_overview=audit_reliability_overview,
            composite_score=composite_score,
            endpoints=endpoints,
            input_lineage=input_lineage,
            methodology_disclosure=methodology_disclosure,
        )
