"""Audit lifecycle constants."""

from __future__ import annotations

LIFECYCLE_STATE_DRAFT = "DRAFT"
LIFECYCLE_STATE_SCHEDULED = "SCHEDULED"
LIFECYCLE_STATE_RUNNING = "RUNNING"
LIFECYCLE_STATE_FINALIZING = "FINALIZING"
LIFECYCLE_STATE_ANALYZING = "ANALYZING"
LIFECYCLE_STATE_REPORTING = "REPORTING"
LIFECYCLE_STATE_COMPLETED = "COMPLETED"
LIFECYCLE_STATE_FAILED = "FAILED"
LIFECYCLE_STATE_CANCELLED = "CANCELLED"

LIFECYCLE_STATES: tuple[str, ...] = (
    LIFECYCLE_STATE_DRAFT,
    LIFECYCLE_STATE_SCHEDULED,
    LIFECYCLE_STATE_RUNNING,
    LIFECYCLE_STATE_FINALIZING,
    LIFECYCLE_STATE_ANALYZING,
    LIFECYCLE_STATE_REPORTING,
    LIFECYCLE_STATE_COMPLETED,
    LIFECYCLE_STATE_FAILED,
    LIFECYCLE_STATE_CANCELLED,
)

TERMINAL_STATES = {
    LIFECYCLE_STATE_COMPLETED,
    LIFECYCLE_STATE_FAILED,
    LIFECYCLE_STATE_CANCELLED,
}

TRANSITIONS: dict[str, tuple[str, ...]] = {
    LIFECYCLE_STATE_DRAFT: (
        LIFECYCLE_STATE_SCHEDULED,
        LIFECYCLE_STATE_CANCELLED,
        LIFECYCLE_STATE_FAILED,
    ),
    LIFECYCLE_STATE_SCHEDULED: (
        LIFECYCLE_STATE_RUNNING,
        LIFECYCLE_STATE_CANCELLED,
        LIFECYCLE_STATE_FAILED,
        LIFECYCLE_STATE_FINALIZING,
    ),
    LIFECYCLE_STATE_RUNNING: (
        LIFECYCLE_STATE_FINALIZING,
        LIFECYCLE_STATE_FAILED,
        LIFECYCLE_STATE_CANCELLED,
    ),
    LIFECYCLE_STATE_FINALIZING: (
        LIFECYCLE_STATE_ANALYZING,
        LIFECYCLE_STATE_COMPLETED,
        LIFECYCLE_STATE_FAILED,
    ),
    LIFECYCLE_STATE_ANALYZING: (LIFECYCLE_STATE_REPORTING, LIFECYCLE_STATE_FAILED),
    LIFECYCLE_STATE_REPORTING: (LIFECYCLE_STATE_COMPLETED, LIFECYCLE_STATE_FAILED),
    LIFECYCLE_STATE_COMPLETED: (),
    LIFECYCLE_STATE_FAILED: (),
    LIFECYCLE_STATE_CANCELLED: (),
}
