"""Scheduling constants and taxonomy."""

from __future__ import annotations

SCHEDULE_TYPE_BASELINE = "baseline"
SCHEDULE_TYPE_BURST = "burst"
SCHEDULE_TYPE_REPEATED = "repeated"
SCHEDULE_TYPE_FINALIZATION = "finalization"
EXECUTION_SCHEDULE_TYPES = (SCHEDULE_TYPE_BASELINE, SCHEDULE_TYPE_BURST, SCHEDULE_TYPE_REPEATED)
SCHEDULE_TYPES = (*EXECUTION_SCHEDULE_TYPES, SCHEDULE_TYPE_FINALIZATION)

BASELINE_DEFAULT_INTERVAL_MINUTES = 15
DEFAULT_AUDIT_WINDOW_HOURS = 48
MAX_BASELINE_OCCURRENCES_PER_AUDIT = 192

MAX_REQUESTS_PER_RUN = 100
MAX_CONCURRENCY = 5
MAX_BURST_REQUESTS_PER_WINDOW = 500
MAX_REPEATED_ITERATIONS = 100
MAX_AUDIT_WINDOW_HOURS = 48

PROD_MAX_REQUESTS_PER_RUN = 25
PROD_MAX_CONCURRENCY = 2
PROD_MAX_BURST_REQUESTS_PER_WINDOW = 100
PROD_REQUIRES_EXPLICIT_ALLOW_PRODUCTION = True

SCENARIO_BASELINE_HEALTH = "baseline_health"
SCENARIO_REPEATED_STABILITY = "repeated_stability"
SCENARIO_BURST_STABILITY = "burst_stability"
SCENARIO_INVALID_PAYLOAD_HANDLING = "invalid_payload_handling"
SCENARIO_MISSING_FIELDS_VALIDATION = "missing_fields_validation"
SCENARIO_AUTH_FAILURE_HANDLING = "auth_failure_handling"
SCENARIO_TIMEOUT_SENSITIVITY = "timeout_sensitivity"
SCENARIO_RESPONSE_CONSISTENCY = "response_consistency"

SCENARIO_TYPES = (
    SCENARIO_BASELINE_HEALTH,
    SCENARIO_REPEATED_STABILITY,
    SCENARIO_BURST_STABILITY,
    SCENARIO_INVALID_PAYLOAD_HANDLING,
    SCENARIO_MISSING_FIELDS_VALIDATION,
    SCENARIO_AUTH_FAILURE_HANDLING,
    SCENARIO_TIMEOUT_SENSITIVITY,
    SCENARIO_RESPONSE_CONSISTENCY,
)

RELIABILITY_CATEGORY_BY_SCENARIO = {
    SCENARIO_BASELINE_HEALTH: "Stability",
    SCENARIO_REPEATED_STABILITY: "Stability",
    SCENARIO_BURST_STABILITY: "Stability",
    SCENARIO_RESPONSE_CONSISTENCY: "Stability",
    SCENARIO_TIMEOUT_SENSITIVITY: "Resilience",
    SCENARIO_AUTH_FAILURE_HANDLING: "Resilience",
    SCENARIO_INVALID_PAYLOAD_HANDLING: "Validation Robustness",
    SCENARIO_MISSING_FIELDS_VALIDATION: "Validation Robustness",
}
